name: influxdb
version: 0.10.0
appVersion: 1.4
description: Scalable datastore for metrics, events, and real-time analytics.
keywords:
- influxdb
- database
- timeseries
home: https://www.influxdata.com/time-series-platform/influxdb/
sources:
- https://github.com/influxdata/influxdb
maintainers:
- name: jackzampolin
  email: jack@influxdb.com
engine: gotpl
icon: https://i.pinimg.com/originals/ed/24/9a/ed249a9a60065ad0e83f2636d329ac41.jpg