sudo: true

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - MAKEFLAGS="-j 2"

script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t n0k0/corvix corvix/
      - docker images
      - docker tag latest $DOCKER_USERNAME/corvix
      - docker push $DOCKER_USERNAME/corvix
