apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: {{ .Release.Name }}
spec:
  selector:
    app: influxdb
  type: NodePort
  ports:
  - name: influxmgmt
    port: 8086
    targetPort: 8086
    nodePort: 30086
