apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-volume
  namespace: tick
  labels:
    app: influxdb
spec:
  hostPath:
    path: "/var/kubernetes-volumes/influx"
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual