name: chronograf
version: 0.4.5
appVersion: 1.3
description: Open-source web application written in Go and React.js that provides
  the tools to visualize your monitoring data and easily create alerting and automation
  rules.
keywords:
- chronograf
- visualizaion
- timeseries
home: https://www.influxdata.com/time-series-platform/chronograf/
maintainers:
- name: Jack Zampolin
  email: jack@influxdb.com
engine: gotpl
icon: https://i.pinimg.com/originals/ed/24/9a/ed249a9a60065ad0e83f2636d329ac41.jpg