apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf-deployment
  namespace: {{ .Release.Name }}
  labels:
    app: chronograf
spec:
  replicas: 1
  template:
    metadata:
      name: chronograf-deployment
      labels:
        app: chronograf
    spec:
      containers:
      - name: chronograf
        image: chronograf
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /var/lib/chronograf
            name: chronograf-storage
        ports:
          - containerPort: 8888
        env:
        - name: INFLUXDB_URL
          value: http://influxdb:8086
        - name: INFLUXDB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: influxdb-creds
        - name: INFLUXDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: influxdb-creds

      restartPolicy: Always
      volumes:
        - name: chronograf-storage
          persistentVolumeClaim:
            claimName: chronograf-volume-claim
  selector:
    matchLabels:
      app: chronograf
