apiVersion: v1
kind: PersistentVolume
metadata:
  name: chronograf-volumes
  namespace: tick
  labels:
    app: chronograf
spec:
  hostPath:
    path: "/var/kubernetes-volumes/chronograf"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual