apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-volume-claim
  namespace: tick
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
