apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-volume-claim
  namespace: tick
  labels:
    app: influxdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: influxdb
  resources:
    requests:
      storage: 10Gi
